name: Basic Practice Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  practice-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Print Message
        run: echo "Hello Sandeep ðŸš€ GitHub Actions is working!"

      - name: Check Node Version
        run: node -v
